### ISSUE TITLE
Example docs are wrong/old?

### ISSUE THREAD

**Issue by 0xTranqui** [ourzora/zdk#80]
@iainnash just discovered some issues in the example docs we provide on the readme for the zdk for getting set up. 

this is what we have:

const zdk = new ZDK({
  endpoint: API_ENDPOINT,
  networks: [
    {
      chain: Chain.Mainnet,
      network: Network.Ethereum,
    },
  ],
  apiKey: API_KEY // optional!
);

this is what it should be:

const zdk = new ZDK({
    endpoint: API_ENDPOINT,
    networks: [
        {
            chain: ZDKChain.Mainnet,
            network: ZDKNetwork.Ethereum
        }
    ]
})

notice that the current version is missing the "ZDK" tag on ZDKChain and ZDKNetwork. Wiithout those (what is currently shown on the readme) you are unable to identify the correct params

**Comment by 0xTranqui** [comment]
just realized the formatting looked completely wrong on that comment ^ so adding screenshots here for further clarification

current:

<img width="311" alt="Screen Shot 2022-10-01 at 11 45 03 PM" src="https://user-images.githubusercontent.com/93691906/193441669-2788dd36-b242-4169-a352-471c7f1b9fd8.png">

what it should be:

![Screen Shot 2022-10-01 at 11 45 20 PM](https://user-images.githubusercontent.com/93691906/193441682-dc0fbe31-b2cf-43cb-b7a3-c6dbe50253fe.png)

**Comment by iainnash** [comment]
Fixed in #81
